version: "3"

services:
  nrk-rss:
    build:
      context: ./app
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - rss-data:/data
  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - rss-data:/usr/share/nginx/html:ro
volumes:
  rss-data:
