version: "3"

services:
  nrk-rss:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - rss-data:/data
      - persistent:/persistent
      - ./config:/config
  web:
    restart: always
    image: nginx
    ports:
      - 8000:80
    volumes:
      - rss-data:/usr/share/nginx/html:ro
volumes:
  rss-data:
  persistent:
